services:
  mongo:
    image: mongo:7.0
    restart: always
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand('ping').ok"]
      interval: 10s
      timeout: 5s
      retries: 5

  node:
    build:
      context: backend-API
      dockerfile: Dockerfile.prod
    ports:
      - "3000:3000"
    env_file:
      - backend-API/.env
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - app-network
    restart: always

  vite:
    build:
      context: admin-dashboard
      dockerfile: Dockerfile.prod
    ports:
      - "4173:4173"
    env_file:
      - admin-dashboard/.env
    depends_on:
      - node
    restart: always
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
