services:
  mongo:
    image: mongo:7.0
    restart: always
    ports:
      - "27017:27017" 
    volumes:
      - mongo-data:/data/db
  node:
    build:
      context: backend-API
      dockerfile: Dockerfile.prod
    container_name: backend
    ports:
      - "3000:3000" 
    env_file:
      - backend-API/.env
    depends_on:
      - mongo
  vite:
    build:
      context: admin-dashboard
      dockerfile: Dockerfile.prod
    container_name: frontend
    environment:
      - VITE_API_URI=http://31.297.35.91
    ports:
      - "4173:4173" 
    depends_on:
      - node
    restart: unless-stopped

volumes:
  mongo-data:
